@seimit Fixing github issue #66 : STDF Linting --> enable Black when writing code
Semi-ATE/Semi-ATE pull request #69
Opened 2021-02-09 17:46 UTC by seimit

2021-02-09 20:39 UTC, seimit commented
I'm done, please make review.

2021-02-10 06:50 UTC, nerohmot requested changes
Black is re-formatting correctly, however sometimes there are regions we don't want black to re-format. 
In our case, the definition section of the records is much more readable when it is not formatted with black.
To do this you can use `# fmt: off` / `# fmt: on` to mark the beginning and end of such a block.

2021-02-10 06:57 UTC, nerohmot requested changes
Can you also change the old style string substitutions like `"%s object creation error: unsupported version '%s'" % (self.id, version)` into the new style `f"{self.id} object creation error: unsupported version '{version}'"`

2021-02-10 08:24 UTC, nerohmot approved these changes

2021-02-10 08:24 UTC, merged